### ISSUE TITLE
Mobile Touch event swipe

### ISSUE THREAD

**Issue by BackendDevops** [netteria/jq_yt_responsive_gallery#1]
Hi, i lookup into your script but i can not see any options set on mobile touch swipe 
Do you support this event or not?

**Comment by netteria** [comment]
I would have to check. I wrote this script a long time ago and I didn't look at it anymore.

**Comment by BackendDevops** [comment]
Thanks alot, if you can tell me how i can add this feature, i can make changes and open a pr to update your project as a contribution if you ok with that

**Comment by netteria** [comment]
I really don't remember what's in there. Seems like there should be a touchmove. Now, unfortunately, I don't have time to go through it and check it out. I'm sorry.

**Comment by BackendDevops** [comment]
That's ok
